### ISSUE TITLE
tcp unsupported transport

### ISSUE THREAD

**Issue by Bilb** [zeromq/jszmq#19]
Does this library only handles ws:// url? I tried to open a connection with 
```
  dealer = new zmq.Dealer();
  dealer.connect('tcp://127.0.0.1:1190');
```

And I just get a unsupported transport error.
But on the samples, there are some with a tcp protocol: https://github.com/zeromq/jszmq#pushpull

What am I missing? thanks

**Comment by DonJayamanne** [comment]
Same here, looking at the code it isn't supported.

**Comment by Bilb** [comment]
yeah saw this. Closing it
