### ISSUE TITLE
how to work with pyzmq 

### ISSUE THREAD

**Issue by wwj718** [zeromq/jszmq#9]
Hi,
I want to make it work with pyzmq:

```python
# python rep.py
import zmq
import time
import sys

port = "8001"
context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:%s" % port)

while True:
    #  Wait for next request from client
    message = socket.recv()
    print("Received request: ", message)
    time.sleep (1)
    socket.send("World from %s" % port)
```

in my browser:

```js
const zmq = require('jszmq');
const req = zmq.socket('req');
req.connect('ws://127.0.0.1:8001');
```

The error message is

`WebSocket connection to 'ws://127.0.0.1:8001/' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE`

what should I do？

Thanks

**Comment by somdoron** [comment]
You need to build libzmq from master with draft enabled and use ws:// on the python side as well

**Comment by wwj718** [comment]
thanks！

**Comment by Elsaligi** [comment]
> You need to build libzmq from master with draft enabled and use ws:// on the python side as well

Thanks for your help. Will it support wss(secure websocket client) also. If not incase any python zmq library available for that?
